wx:
  mp:
    configs:
      - appId: wx5699938bcc90c42d
        secret: f65035505f7aa52bfc6777b5d421096c
        token: hhyyjj
server:
  port: 8200
spring:
  application:
    name: app-db-weixin
  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
mayikt:
  weixin:
    registration:
       code:
       ###微信注册码消息
        message:  您的注册码为:%s，请关注<a href="https://www.baidu.com">免费公开</a>，期待你的加入，感谢！
    ###默认提示消息
    default:
      registration:
        code:
          message: 您的消息，我们已经收到,会及时回复给您的!
swagger:
  base-package: com.db.service